
@hostName = localhost
@port = 5205

@host = http://{{hostName}}:{{port}}



###
POST {{host}}/api/signUp
Content-Type: application/json

{
  "username": "string",
  "email": "string",
  "password": "string",
  "firstName": "string",
  "lastName": "string"
}

###
GET {{host}}/api/users

###
GET {{host}}/api/users/c2782a57-513e-4f72-ba6c-8345b86f3ef7