
@hostName = localhost
@port = 5205

@host = http://{{hostName}}:{{port}}



###
POST {{host}}/api/signUp
Content-Type: application/json

{
  "username": "string",
  "email": "string",
  "password": "string",
  "firstName": "string",
  "lastName": "string"
}

###
GET {{host}}/api/users

###
GET {{host}}/api/users/aac85f4d-34ac-4712-a783-52424c96ef3a